/**
 * codegenが出力するenumのunion型から実行時値(const+type)を生成する
 *
 * graphql-modulesプリセットは型ファイルの生成時にenumsAsTypes: trueを
 * 強制するため、codegen単体ではenumの値定義を出力できない。
 * @see https://github.com/dotansimha/graphql-code-generator/issues/6023
 */

import fs from "node:fs";

const BASE_TYPES_PATH = "src/app/graphql/types.generated.ts";

// enum名と出力先ファイルパスの対応。スキーマにenumを追加した場合はここに追記すること
const OUTPUT_PATHS: Record<string, string> = {
  ErrorCode: "src/modules/shared/presentation/ErrorCode.ts",
  TodoSortKeys: "src/modules/todo/presentation/TodoSortKeys.ts",
  TodoStatus: "src/modules/todo/presentation/TodoStatus.ts",
};

if (!fs.existsSync(BASE_TYPES_PATH)) {
  throw new Error(`${BASE_TYPES_PATH} not found. Run graphql-codegen before this script.`);
}

const baseTypes = fs.readFileSync(BASE_TYPES_PATH, "utf-8");

const unionPattern = /export type (\w+) =((?:\s*\| '[^']+')+);/g;
const literalPattern = /'([^']+)'/g;

type EnumDef = { name: string; values: string[] };

const enums: EnumDef[] = [];
for (const match of baseTypes.matchAll(unionPattern)) {
  const name = match[1]!;
  const body = match[2]!;
  const values = [...body.matchAll(literalPattern)].map((m) => m[1]!);
  enums.push({ name, values });
}

const unknown = enums.filter(({ name }) => !(name in OUTPUT_PATHS));
if (unknown.length > 0) {
  throw new Error(
    `Unmapped enums found in ${BASE_TYPES_PATH}: ${unknown.map(({ name }) => name).join(", ")}. Add entries to OUTPUT_PATHS.`,
  );
}
if (enums.length !== Object.keys(OUTPUT_PATHS).length) {
  throw new Error(
    `Enums in OUTPUT_PATHS missing from ${BASE_TYPES_PATH}: ${Object.keys(OUTPUT_PATHS)
      .filter((name) => !enums.some(({ name: n }) => n === name))
      .join(", ")}`,
  );
}

const toPascalCase = (screamingSnakeCase: string): string =>
  screamingSnakeCase
    .toLowerCase()
    .split("_")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join("");

for (const { name, values } of enums) {
  const entries = values.map((value) => `  ${toPascalCase(value)}: "${value}",`);
  const content = [
    "// This file is auto-generated by enum-codegen.ts. Do not edit it manually.",
    "",
    `export const ${name} = {`,
    ...entries,
    "} as const;",
    "",
    `export type ${name} = (typeof ${name})[keyof typeof ${name}];`,
    "",
  ].join("\n");

  fs.writeFileSync(OUTPUT_PATHS[name]!, content, "utf-8");
}
