[tools]
node = "24.10"
pnpm = "11.15"
oxlint = { version = "apps_v1.76.0", matching = "oxlint", rename_exe = "oxlint" }
# cli実行用高速バイナリ、`--lsp`オプションなし、prettierなし
oxfmtbin = { version = "apps_v1.76.0", matching = "oxfmt", rename_exe = "oxfmtbin" }
# バイナリ補助用
prettier = "3.9.6"
# エディタ用npm版パッケージ、`--lsp`オプションあり、prettier同梱
oxfmt = "0.61"

[tool_alias]
oxlint = "github:oxc-project/oxc"
oxfmtbin = "github:oxc-project/oxc"

[env]
_.file = ".env"
_.path = ['{{config_root}}/node_modules/.bin']

[tasks.setup]
depends = ["setup:env"]
env = { _.file = ".env" } # dependsで.envが作成される場合があるので必要
run = """
pnpm install
${COMPOSE_CMD:?} down -v db
${COMPOSE_CMD:?} up --wait db
pgschema apply --file db/schema.sql --auto-approve
node db/seed.minimal.ts
"""

[tasks."setup:env"]
hide = true
run = """
test -f .env || cp .env.example .env
"""

[tasks.dev]
depends = ["up:dev"]
run = """
node --watch --import ./src/instrumentation.ts src/presentation/server.ts
"""

[tasks.check]
depends = ["check:*"]

[tasks."check:type"]
run = """
tsc
"""

[tasks."check:style"]
run = """
oxlint
"""

[tasks."check:format"]
run = """
oxfmtbin --check
"""

[tasks."check:format-prettier"]
run = """
prettier --cache --check './**/*.{yml,yaml,md}' '!pnpm-lock.yaml'
"""

[tasks.build]
run = """
vite build
"""

[tasks.preview]
depends = ["build", "up:all"]
env = { _.file = [".env.preview"] }
run = """
node --enable-source-maps --import ./dist/instrumentation.js dist/server.js
"""

[tasks.test]
depends = ["test:ut", "test:it", "test:e2e"]

[tasks."test:ut"]
env = { _.file = [{ path = ".env.test", expand = true }] }
run = """
vitest --project ut
"""

[tasks."test:it"]
depends = ["test:setup"]
env = { _.file = [{ path = ".env.test", expand = true }] }
run = """
vitest --project it
"""

[tasks."test:e2e"]
depends = ["test:setup"]
wait_for = ["test:it"]
env = { _.file = [{ path = ".env.test", expand = true }] }
run = """
vitest --project e2e
"""

[tasks."test:setup"]
hide = true
depends = ["up:test"]
env = { _.file = [{ path = ".env.test", expand = true }] }
run = """
pgschema apply --file db/schema.empty.sql --auto-approve
pgschema apply --file db/schema.sql --auto-approve
"""

[tasks."db:typegen"]
depends = ["up:db"]
run = """
kysely-codegen --config-file kysely-codegen.ts
"""

[tasks."db:seed-minimal"]
depends = ["up:db"]
run = """
node db/seed.minimal.ts
"""

[tasks."db:seed-bulk"]
depends = ["up:db"]
run = """
node db/seed.bulk.ts
"""

[tasks."gql:codegen"]
run = """
node schemagen.ts
oxfmt schema.graphql
graphql-codegen-esm
"""

[tasks."up:db"]
hide = true
run = """
${COMPOSE_CMD:?} up --wait db
"""

[tasks."up:dev"]
hide = true
run = """
${COMPOSE_CMD:?} up --wait db valkey aspire-dashboard
"""

[tasks."up:test"]
hide = true
env = { _.file = [{ path = ".env.test", expand = true }] }
run = """
${COMPOSE_CMD:?} up --wait db valkey
"""

[tasks."up:all"]
hide = true
run = """
${COMPOSE_CMD:?} up --wait
"""
