/**
 * 実行時のSDL読み込みを回避するため、静的import可能なTSモジュールを生成する
 */

import fs from "node:fs";

const SDL_PATH = "schema.graphql";

if (!fs.existsSync(SDL_PATH)) {
  throw new Error(`${SDL_PATH} not found. Run graphql-codegen before this script.`);
}

const sdl = fs.readFileSync(SDL_PATH, "utf-8");

const lines = [
  "// This file is auto-generated by typedefs-codegen.ts. Do not edit it manually.",
  `export const typeDefs: string = ${JSON.stringify(sdl)};`,
  "",
];

fs.writeFileSync("src/app/graphql/type-defs.generated.ts", lines.join("\n"), "utf-8");
