extend type Mutation {
  """
  ログイン済のみ
  """
  accountPasswordChange(
    """
    8文字以上、50文字まで
    """
    oldPassword: String!

    """
    8文字以上、50文字まで
    """
    newPassword: String!
  ): AccountPasswordChangeResult @semanticNonNull @complexity(value: 1000)
}

union AccountPasswordChangeResult =
  | AccountPasswordChangeSuccess
  | InvalidInputErrors
  | NewPasswordSameAsOldError
  | IncorrectOldPasswordError

type AccountPasswordChangeSuccess {
  user: User!
}

type NewPasswordSameAsOldError implements Error {
  message: String!
}

type IncorrectOldPasswordError implements Error {
  message: String!
}
