// This file is auto-generated by enum-codegen.ts. Do not edit it manually.

export const ErrorCode = {
  AccessTokenExpired: "ACCESS_TOKEN_EXPIRED",
  AuthenticationError: "AUTHENTICATION_ERROR",
  BadUserInput: "BAD_USER_INPUT",
  Forbidden: "FORBIDDEN",
  InternalServerError: "INTERNAL_SERVER_ERROR",
  QueryTooComplex: "QUERY_TOO_COMPLEX",
  RateLimited: "RATE_LIMITED",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
