// This file is auto-generated by enum-codegen.ts. Do not edit it manually.

export const TodoSortKeys = {
  CreatedAt: "CREATED_AT",
  UpdatedAt: "UPDATED_AT",
} as const;

export type TodoSortKeys = (typeof TodoSortKeys)[keyof typeof TodoSortKeys];
