// This file is auto-generated by enum-codegen.ts. Do not edit it manually.

export const TodoStatus = {
  Done: "DONE",
  Pending: "PENDING",
} as const;

export type TodoStatus = (typeof TodoStatus)[keyof typeof TodoStatus];
